name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
      - release/*

env:
  DOCKER_IMAGE: rob2k2/cihomework

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate image tag (Windows CMD)
        id: version
        shell: cmd
        run: |
          for /f "tokens=1-3 delims=/ " %%a in ("%date%") do (
            set DATE=%%c.%%a.%%b
          )
          echo TAG=v%DATE%-${{ github.run_number }}>> %GITHUB_ENV%

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}
            ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Summary
        run: |
          echo "✅ Imagen subida correctamente:"
          echo "- latest"
          echo "- ${{ env.TAG }}"
          echo "- ${{ github.ref_name }}"
          echo "- ${{ github.sha }}"
